In [1]:
import pandas as pd
import numpy as np #importing the required library

In [2]:
dataset = pd.read_csv("DigitalAd_dataset.csv")
dataset.head(100) #load the dataset

Age  Salary  Status
0    18   82000       0
1    29   80000       0
2    47   25000       1
3    45   26000       1
4    46   28000       1
..  ...     ...     ...
95   38   80000       0
96   39   71000       0
97   37   71000       0
98   38   61000       0
99   37   55000       0

[100 rows x 3 columns]

In [3]:
print(dataset.shape)
print(dataset.head(10)) # verify the dataset

(400, 3)
   Age  Salary  Status
0   18   82000       0
1   29   80000       0
2   47   25000       1
3   45   26000       1
4   46   28000       1
5   48   29000       1
6   45   22000       1
7   47   49000       1
8   48   41000       1
9   45   22000       1


In [4]:
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values # splitting the dataset columns into x,y columns. x contains 2 columns, y contains 1 column as a output column
x

array([[    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],
       [    27,  17000],
       [    33,  51000],
       [    35, 108000],
       [    30,  15000],
       [    28,  84000],
       [    23,  20000],
       [    25,  79000],
       [    27,  54000],
       [    30, 135000],
       [    31,  89000],
       [    24,  32000],
       [    18,  44000],
       [    29,  83000],
       [    35,  23000],


In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.20,random_state=126)#train and test for the split dataset

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
print(x_train)#this is for the standardized the column values into a single based column value

[[-1.89545740e-01 -4.68245374e-01]
 [ 9.40664885e-01  1.03221139e-01]
 [-1.89545740e-01 -5.25392025e-01]
 [-9.53615215e-02 -5.25392025e-01]
 [ 6.58112228e-01  2.46087767e-01]
 [ 1.87191135e-01  2.04620728e+00]
 [-3.77914178e-01 -1.29687182e+00]
 [-5.66282615e-01 -1.49688510e+00]
 [ 1.97669129e+00  2.07478061e+00]
 [ 1.88250707e+00  2.10335393e+00]
 [-1.79067746e+00  4.17527721e-01]
 [-1.89545740e-01  8.17554279e-01]
 [ 9.30069160e-02 -8.11125281e-01]
 [ 2.81375353e-01 -1.15400519e+00]
 [ 1.03484910e+00  5.03247698e-01]
 [ 9.30069160e-02  1.88941116e-01]
 [ 3.75559572e-01  2.74661093e-01]
 [-1.41394058e+00 -1.43973844e+00]
 [ 7.52296447e-01 -1.09685854e+00]
 [-1.13138793e+00  2.74661093e-01]
 [-1.17730273e-03  2.74661093e-01]
 [-1.50812480e+00  3.03234418e-01]
 [-2.83729959e-01 -1.38259179e+00]
 [ 3.75559572e-01 -4.68245374e-01]
 [-2.83729959e-01  5.03247698e-01]
 [ 1.41158598e+00  4.60744876e-02]
 [ 9.30069160e-02 -8.11125281e-01]
 [-1.22557215e+00 -1.06828521e+00]
 [-1.79067746e+00 -1

In [7]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train) # train the model logistic regression

LogisticRegression()

In [8]:
y_pred = model.predict(x_test)
#using x_test the y_pred should be predict

In [9]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

print("accuracy score of the model: {0}%".format(accuracy_score(y_test, y_pred)*100))#verify the accuracy of the model

[[55  2]
 [ 7 16]]
accuracy score of the model: 88.75%


In [10]:
age = int(input("Enter the customer age :"))
sal = int(input("Enter the customer salary :"))
newcust = [[age,sal]]
result = model.predict(sc.transform(newcust))
print(result)
if result == 1:
    print("The customer will buy")
else:
    print("The customer will not buy")# give the input values and check wheather this is working or not.

Enter the customer age :45
Enter the customer salary :50000
[0]
The customer will not buy
